### ISSUE TITLE
PlaySysSound is undefined

### ISSUE THREAD

**Issue by haseeb-islam** [trietho/react-native-a-beep#1]
i am facing this issue PlaySysSound is undefined

**Comment by trietho** [comment]
Hi Haseebb, 
Please share your example code.

Thanks

**Comment by haseeb-islam** [comment]
import RNBeep from 'react-native-a-beep';


<Button onPress={() => {RNBeep.beep() }} title="Beep Success"></Button>
    <Button onPress={() => {RNBeep.beep(false) }} title="Beep Fail"></Button>
    <Button onPress={() => {RNBeep.PlaySysSound(RNBeep.AndroidSoundIDs.TONE_CDMA_ABBR_ALERT) }} title="Beep Android Custom"></Button>
    <Button onPress={() => {RNBeep.PlaySysSound(RNBeep.iOSSoundIDs.AudioToneBusy) }} title="Beep iOS Custom"></Button>
<img width="363" alt="Screenshot 2019-04-29 at 3 17 15 PM" src="https://user-images.githubusercontent.com/38561017/56890105-fb464780-6a91-11e9-8437-d175033bab15.png">

**Comment by trietho** [comment]
You may try a clean install of your npm packages firstly.

**Comment by haseeb-islam** [comment]
i did but nothing happened.

**Comment by haseeb-islam** [comment]
yahoooo issue solved . issue was in linking in ios . by manually linking issue will solve.

**Comment by trietho** [comment]
Good to hear!
