### ISSUE TITLE
android not working

### ISSUE THREAD

**Issue by rendomnet** [trietho/react-native-a-beep#11]
react native 0.63.3

android not working
RNBeep.beep();

**Comment by obie3** [comment]
I have same challenge, pls any heads up??

**Comment by trietho** [comment]
Hi @rendomnet 

I just tested with react-native 0.6.3 without any problem

Steps:
1. react-native init testBeep
2. cd testBeep
3. yarn install react-native-a-beep
4. add example code into App.js

<img width="334" alt="Screen Shot 2020-12-01 at 9 57 46 AM" src="https://user-images.githubusercontent.com/814017/100691629-b09e5700-33bb-11eb-9198-cdb6c90c91a0.png">
Feel free to reopen if you still meet the problem

**Comment by obie3** [comment]
oh great!, thanks I found my way around it long ago.
