### ISSUE TITLE
Blank screen after install

### ISSUE THREAD

**Issue by rafwell** [trietho/react-native-a-beep#13]
Hi. After simply add your package to my project he have stopped to work for no reason.

No log, no messages, simply a blank screen after run app. If I remove the package, all is good again.

Some details who I hope help:

I've installed via yarn instead of npm

My app is a bare project, but I use some expo dependencies, like the expo-barcode-scanner.

I'm newbie in react-native, but I have long experience developing in ionic and web apps, so it can be a my problem, but I cant find a reason. In my search I've found some discussions asking for me adding the NDK to the project, I've it did, but the problem persist. 

Maybe have some dependency who I need install before use it or some configuration?

Thanks.

**Comment by trietho** [comment]
Hi @rafwell, please refer to https://github.com/trietho/react-native-a-beep/issues/11
