### ISSUE TITLE
npm peer dependancy error

### ISSUE THREAD

**Issue by jlguenego** [trietho/react-native-a-beep#23]
D:\__FRN\geoloc\tracking>npm install react-native-a-beep
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tracking@0.0.7
npm ERR! Found: react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.64.1" from react-native-a-beep@1.1.0
npm ERR! node_modules/react-native-a-beep
npm ERR!   react-native-a-beep@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jlouis\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jlouis\AppData\Local\npm-cache\_logs\2022-06-17T17_25_03_761Z-debug-0.log

What I would recommand is to put a peer dependancy with ~, and not ^.

**Comment by Yasir12598** [comment]
Same issue
