### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by yankovalera** [trietho/react-native-a-beep#4]
When I run pod install, I'm getting this:

[!] The `RNReactNativeABeep` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.

**Comment by trietho** [comment]
Hi @yankovalera 
I just merged a Pull Request that enable CocaPods Install, please help double check. Thanks to @MuhammadNayabButt for the pull request.

**Comment by yankovalera** [comment]
hi @trietho looks like if I try to install, I'm getting same version as before (with the error). New version has been released?

**Comment by trietho** [comment]
Oops, my bad! I forgot releasing it to npmjs. I just publish the latest code npmjs and I think you can try again. Thank you very much for your response, @yankovalera.

**Comment by jeffmon** [comment]
Hello @trietho,

I'm running the latest and `pod install` is running fine. I run into issues when trying to run `RNBeep.beep();`, I get this error:

![IMG_3191](https://user-images.githubusercontent.com/18548300/66102972-dded3c00-e54f-11e9-8d26-4746d59b8d47.jpg)

Any help would be appreciated, thank you!

**Comment by yankovalera** [comment]
Same here

**Comment by trietho** [comment]
@yankovalera @jeffmon I met the same issue. Please use the version 1.0.2 in the old fashion way while waiting for the fix. Thanks for let me know.

**Comment by jeffmon** [comment]
@trietho 

I'm running version `1.0.2` and it runs fine in a simulator, but if I try to run it on my phone via Xcode, I get this error:

<img width="453" alt="Screen Shot 2019-10-03 at 7 52 58 AM" src="https://user-images.githubusercontent.com/18548300/66151508-2d188880-e5b3-11e9-94ed-95a003103081.png">

Thanks for your help on this!

**Comment by jeffmon** [comment]
I was able to fix it by manually fixing `/node_modules/react-native/React/RCTBridgeModule.h`, replacing `#import "RCTDefines.h"` on line 10, with:

```
#if __has_include("RCTDefines.h")
#import "RCTDefines.h"
#else
#import <React/RCTDefines.h>
#endif
```

To continue this route I have to use https://github.com/ds300/patch-package for now to patch this.

**Comment by trietho** [comment]
@jeffmon @yankovalera Version 1.0.5 was released to npmjs. I tested. pod install will work as it is.

**Comment by triethowvn** [comment]
There is no comment in 20 days, so I think the problem was resolved at your side.
