### ISSUE TITLE
Error occured while calling RNBeep.() function

### ISSUE THREAD

**Issue by jenipharachel** [trietho/react-native-a-beep#9]
I want a beep sound when there is an alert message occuring in my code

My code spnippet:
```
else if (dovalue != "") {
      this.showAlertMessage("Failure", "Invalid DO/Invoice");
      RNBeep.beep(false);
      //alert("Delivery order does not exist in this Delivery Note.");
      this.setState({
        DoTextValue: ""
      });
      textInput.focus();
    }
```

When this alert occurs in my code, instead of the alert and beep sound, I'm receiving the below error 
![Screenshot_2020-03-24-12-42-34-830_com aurora](https://user-images.githubusercontent.com/35962711/77398220-2124bb00-6dcd-11ea-89e8-78605d8ca48d.png)

**Comment by jasonseck** [comment]
i'm on RN version 0.61.1 and here's how i got it to work. you need to also install the pod, but the podspec file is not in the correct directory. go to the node_modules/react-native-a-beep directory and copy RNReactNativeABeep from the ios folder to the react-native-a-beep folder.

in {$project}/node_modules/react-native-a-beep/ios 
cp ./RNReactNativeABeep ..

then go back to your ios folder and pod install..

should work.

**Comment by krakzk** [comment]
Im facing the same issue, RN 0.59.3
This is in android.
I have traced back the issue that the NativeModules is not able to import the Module from android. It shows undefined.
Could you please check?

**Comment by krakzk** [comment]
Resolved after linking, as per given in ReadMe2. Please add that in readme also. :)
